PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Controllers/LibroController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class LibroController : Controller
    {
        [HttpGet]
        public ActionResult GetByAutor(ML.Libro libro)
        {
            using(HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApi"].ToString());
                var responseTask = client.GetAsync("GetByAutor/{autor}?autor="+libro.Autor);
                responseTask.Wait();

                List<object> libros = new List<object>();
                var respuesta = responseTask.Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    var readTask = respuesta.Content.ReadAsAsync<Dictionary<string, object>>(); //Instalar NuGet Microsoft.AspNet.WebApi.Client
                    readTask.Wait();
                    if(readTask.Result.TryGetValue("Libros", out object libroObject) && libroObject != null)
                    {
                        libros = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(libroObject.ToString());
                    }
                    
                    libro.Libros = new List<ML.Libro>();

                    foreach(var jsonLibro in libros)
                    {
                        ML.Libro libroDes = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Libro>(jsonLibro.ToString());
                        libro.Libros.Add(libroDes);
                    }
                }
                else
                {

                }
            }

            return View(libro);
        }

        [HttpGet]
        public ActionResult GetByTitulo(ML.Libro libro)
        {
            using(HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApi"].ToString());
                var responseTask = client.GetAsync("GetByTitulo/{titulo}?titulo=" + libro.TituloLibro);
                responseTask.Wait();

                List<object> libros = new List<object>();
                var respuesta = responseTask.Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    var readTask = respuesta.Content.ReadAsAsync<Dictionary<string, object>>();
                    readTask.Wait();
                    if(readTask.Result.TryGetValue("Libros", out object libroObject) && libroObject != null)
                    {
                        libros = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(libroObject.ToString());
                    }

                    libro.Libros = new List<ML.Libro>();

                    foreach(var jsonLibro in  libros)
                    {
                        ML.Libro libroDes = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Libro>(jsonLibro.ToString());
                        libro.Libros.Add(libroDes);
                    }
                }
                else
                {
                    throw new Exception();
                }
            }

            return View("GetByAutor", libro);
        }

        [HttpGet]
        public ActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Form(ML.Libro libro)
        {
            Dictionary<string,object> result = new Dictionary<string, object>();
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApi"].ToString());
                var responseTask = client.PostAsJsonAsync("Add", libro);
                responseTask.Wait(); // Llamada al metodo de la api
                var respuesta = responseTask.Result;
                if (respuesta.IsSuccessStatusCode)
                {
                    var readTask = respuesta.Content.ReadAsAsync<Dictionary<string, object>>();
                    readTask.Wait();
                    result = readTask.Result;

                }
                else
                {
                    var readTask = respuesta.Content.ReadAsAsync<Dictionary<string, object>>();
                    readTask.Wait();
                    result = readTask.Result;
                }
            }
            bool resultado = (bool)result["Resultado"];

            if (resultado == true)
            {
                ViewBag.Mensaje = "El Usuario ha sido insertado";
            }
            else
            {
                string excepcion = (string)result["Excepcion"];
                ViewBag.Mensaje = "el Usuario no se pudo registrar" + excepcion;
            }
            return View();
        }
    }
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Libro/Form.cshtml
@model ML.Libro
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Mensaje != null)
{
    <div class="alert alert-info">
        @ViewBag.Mensaje
    </div>
}

<h2 class="text-center">Formulario Libro</h2>

<hr />

@using (Html.BeginForm("Form", "Libro", FormMethod.Post))
{
    <div class="bg-formulario" style="font-weight:600; color: white;">
        <div class="row justify-content-center">
            <div class="col d-flex flex-column align-items-center">
                @Html.LabelFor(model => model.TituloLibro, "Titulo del libro")
                @Html.TextBoxFor(model => model.TituloLibro, new { @class = "form-control text-center", @placeholder = "Título" })
            </div>
            <div class="col d-flex flex-column align-items-center">
                @Html.LabelFor(model => model.Autor)
                @Html.TextBoxFor(model => model.Autor, new { @class = "form-control text-center", @placeholder = "Autor del libro" })
            </div>
            <div class="col d-flex flex-column align-items-center">
                @Html.LabelFor(model => model.Editorial)
                @Html.TextBoxFor(model => model.Editorial, new { @class = "form-control text-center", @placeholder = "Editorial del libro" })
            </div>
        </div>

        <div class="d-flex flex-column align-items-center mt-5">
            @Html.LabelFor(model => model.AñoPublicacion, "Año de publicación")
            @Html.TextBoxFor(model => model.AñoPublicacion, new { @class = "form-control text-center", @placeholder = "Año de publicacion Ej: 2001" })
        </div>
    </div>

    <div class="row justify-content-end mt-4">
        <div class="col-md-1 d-flex flex-column align-items-end">
            <input type="submit" class="btn btn-success" value="Guardar" />
        </div>

        <div class="col-md-1 d-flex flex-column align-items-end">
            <a href="@Url.Action("GetByAutor", "Libro")" class="btn btn-danger">Cancelar</a>
        </div>
    </div>
}

<style>
    .bg-formulario {
        background-color: #565656;
        padding: 3rem 0;
        border-radius: 2.5rem;
        border: 0.2rem solid #e7d23c;
    }
</style>

PL/Views/Libro/GetByAutor.cshtml
@model ML.Libro
@{
    ViewBag.Title = "GetByAutor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Libros</h2>

<hr />


@using (Html.BeginForm("GetByAutor", "Libro", FormMethod.Get))
{
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="input-group">
                @Html.TextBoxFor(model => model.Autor, new { @class = "form-control text-center", @placeholder = "Búsqueda por Autor" })
                <div class="input-group-append">
                    <button type="submit" class="btn btn-dark"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("GetByTitulo", "Libro", FormMethod.Get))
{
    <div class="row justify-content-center mt-3">
        <div class="col-md-4">
            <div class="input-group">
                @Html.TextBoxFor(model => model.TituloLibro, new { @class = "form-control text-center", @placeholder = "Búsqueda por Título" })
                <div class="input-group-append">
                    <button type="submit" class="btn btn-dark"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </div>
    </div>
}

<div class="float-end">
    <a href="@Url.Action("Form", "Libro")" type="button" class="btn btn-primary" style="font-weight: 700">Agregar  <i class="bi bi-plus-circle"></i></a>
</div>




@if (Model == null)
{
    <div class="alert alert-danger" role="alert">
        Error! La lista esta vacia!
    </div>
}
else
{
    <div class="mt-5">
        <table class="table table-dark table-striped text-center">
            <thead>
                <tr>
                    <th>Editar</th>
                    <th>IdLibro</th>
                    <th>Autor</th>
                    <th>Titulo</th>
                    <th>Año</th>
                    <th>Editorial</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Libro libro in Model.Libros)
                {
                    <tr>
                        <td></td>
                        <td>@libro.IdLibro</td>
                        <td>@libro.Autor</td>
                        <td>@libro.TituloLibro</td>
                        <td>@libro.AñoPublicacion</td>
                        <td>@libro.Editorial</td>
                        <td></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Libros", "GetByAutor", "Libro", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>